### ISSUE TITLE
User creation and ssh user creation should use sysprep and cloudinit

### ISSUE THREAD

**Issue by FruityWelsh** [Aristocrat-B2B/terraform-nutanix-virtualmachine#1]
In order to not be limited with vms that don't have the required hostnamectl, sed, and sudo the providers [cloudinit](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/resources/virtual_machine#guest_customization_cloud_init_user_data) and [sysprep](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/resources/virtual_machine#guest_customization_sysprep) arguments instead.

**Comment by pmiles** [comment]
Thank you for this update @FruityWelsh - I'll look into this, this week for you.

**Comment by pmiles** [comment]
Please see version 1.0.1 which implements the functionality you requested.

regards

B2B Devops
