### ISSUE TITLE
feature request: Be able to use project friendly name instead of UUID

### ISSUE THREAD

**Issue by FruityWelsh** [Aristocrat-B2B/terraform-nutanix-virtualmachine#3]
It would make set up more friendly to be able to use project_name (i.e. "test_project) instead of project_uuid. I know project reference requires that uuid, so it would probably have to be a data lookup.

**Comment by pmiles** [comment]
I believe we have a solution for this now - it just needs to be peer reviewed internally @FruityWelsh - so with a bit of luck, should be released tomorrow.

**Comment by pmiles** [comment]
@FruityWelsh - please check out version 1.0.3

You should set:

```
project_id = ""
project_name = "my_project"
```
