### ISSUE TITLE
Error - .terraform/modules/virtualmachine/main.tf line 16 

### ISSUE THREAD

**Issue by Kairos-HY** [Aristocrat-B2B/terraform-nutanix-virtualmachine#5]
An error occurred when I did terraform apply. Please confirm what to do.

![image](https://user-images.githubusercontent.com/87158500/133707151-c963733c-79b6-423d-822b-627acace4c76.png)

**Comment by heerakk** [comment]
Can you please paste a snippet of your terraform code, that generate this error.

**Comment by pmiles** [comment]
Closing issue as its gone stale
